# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_form(object):
    def setupUi(self, edit_form):
        edit_form.setObjectName("edit_form")
        edit_form.resize(432, 445)
        self.verticalLayoutWidget = QtWidgets.QWidget(edit_form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 91, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(edit_form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 60, 281, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.name_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.name_input.setObjectName("name_input")
        self.verticalLayout_2.addWidget(self.name_input)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.qty_selection = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.qty_selection.setObjectName("qty_selection")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.qty_selection.addItem("")
        self.verticalLayout_2.addWidget(self.qty_selection)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setObjectName("widget")
        self.red_radio_button = QtWidgets.QRadioButton(self.widget)
        self.red_radio_button.setGeometry(QtCore.QRect(0, 0, 136, 17))
        self.red_radio_button.setObjectName("red_radio_button")
        self.navy_radio_button = QtWidgets.QRadioButton(self.widget)
        self.navy_radio_button.setGeometry(QtCore.QRect(140, 0, 277, 17))
        self.navy_radio_button.setObjectName("navy_radio_button")
        self.verticalLayout_2.addWidget(self.widget)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.company_code_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.company_code_input.setObjectName("company_code_input")
        self.verticalLayout_2.addWidget(self.company_code_input)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_2.setObjectName("widget_2")
        self.new_buckle_radio_button = QtWidgets.QRadioButton(self.widget_2)
        self.new_buckle_radio_button.setGeometry(QtCore.QRect(0, 0, 136, 17))
        self.new_buckle_radio_button.setObjectName("new_buckle_radio_button")
        self.old_buckle_radio_button = QtWidgets.QRadioButton(self.widget_2)
        self.old_buckle_radio_button.setGeometry(QtCore.QRect(140, 0, 277, 17))
        self.old_buckle_radio_button.setObjectName("old_buckle_radio_button")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_3.setObjectName("widget_3")
        self.yes_urgent_radio_button = QtWidgets.QRadioButton(self.widget_3)
        self.yes_urgent_radio_button.setGeometry(QtCore.QRect(0, 0, 136, 17))
        self.yes_urgent_radio_button.setObjectName("yes_urgent_radio_button")
        self.no_urgent_radio_button = QtWidgets.QRadioButton(self.widget_3)
        self.no_urgent_radio_button.setGeometry(QtCore.QRect(140, 0, 271, 20))
        self.no_urgent_radio_button.setObjectName("no_urgent_radio_button")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.repeats_combo_box = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.repeats_combo_box.setObjectName("repeats_combo_box")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.repeats_combo_box.addItem("")
        self.verticalLayout_2.addWidget(self.repeats_combo_box)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.line = QtWidgets.QFrame(edit_form)
        self.line.setGeometry(QtCore.QRect(20, 370, 391, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(edit_form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 400, 371, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ok_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_4.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_4.addWidget(self.cancel_button)
        self.label_8 = QtWidgets.QLabel(edit_form)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 71, 31))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(edit_form)
        QtCore.QMetaObject.connectSlotsByName(edit_form)

    def retranslateUi(self, edit_form):
        _translate = QtCore.QCoreApplication.translate
        edit_form.setWindowTitle(_translate("edit_form", "Dialog"))
        self.label.setText(_translate("edit_form", "Name"))
        self.label_2.setText(_translate("edit_form", "Qty"))
        self.label_3.setText(_translate("edit_form", "Colour"))
        self.label_4.setText(_translate("edit_form", "Company Code"))
        self.label_5.setText(_translate("edit_form", "Buckle Type"))
        self.label_6.setText(_translate("edit_form", "Urgent y/n"))
        self.label_7.setText(_translate("edit_form", "No. of repeats"))
        self.qty_selection.setItemText(0, _translate("edit_form", "1"))
        self.qty_selection.setItemText(1, _translate("edit_form", "2"))
        self.qty_selection.setItemText(2, _translate("edit_form", "3"))
        self.qty_selection.setItemText(3, _translate("edit_form", "4"))
        self.qty_selection.setItemText(4, _translate("edit_form", "5"))
        self.qty_selection.setItemText(5, _translate("edit_form", "6"))
        self.qty_selection.setItemText(6, _translate("edit_form", "7"))
        self.qty_selection.setItemText(7, _translate("edit_form", "8"))
        self.qty_selection.setItemText(8, _translate("edit_form", "9"))
        self.qty_selection.setItemText(9, _translate("edit_form", "10"))
        self.qty_selection.setItemText(10, _translate("edit_form", "11"))
        self.qty_selection.setItemText(11, _translate("edit_form", "12"))
        self.qty_selection.setItemText(12, _translate("edit_form", "13"))
        self.qty_selection.setItemText(13, _translate("edit_form", "14"))
        self.qty_selection.setItemText(14, _translate("edit_form", "15"))
        self.qty_selection.setItemText(15, _translate("edit_form", "16"))
        self.qty_selection.setItemText(16, _translate("edit_form", "17"))
        self.qty_selection.setItemText(17, _translate("edit_form", "18"))
        self.red_radio_button.setText(_translate("edit_form", "Red"))
        self.navy_radio_button.setText(_translate("edit_form", "Navy"))
        self.new_buckle_radio_button.setText(_translate("edit_form", "New"))
        self.old_buckle_radio_button.setText(_translate("edit_form", "Old"))
        self.yes_urgent_radio_button.setText(_translate("edit_form", "Yes"))
        self.no_urgent_radio_button.setText(_translate("edit_form", "No"))
        self.repeats_combo_box.setItemText(0, _translate("edit_form", "4"))
        self.repeats_combo_box.setItemText(1, _translate("edit_form", "5"))
        self.repeats_combo_box.setItemText(2, _translate("edit_form", "6"))
        self.repeats_combo_box.setItemText(3, _translate("edit_form", "7"))
        self.repeats_combo_box.setItemText(4, _translate("edit_form", "8"))
        self.repeats_combo_box.setItemText(5, _translate("edit_form", "9"))
        self.repeats_combo_box.setItemText(6, _translate("edit_form", "10"))
        self.repeats_combo_box.setItemText(7, _translate("edit_form", "11"))
        self.repeats_combo_box.setItemText(8, _translate("edit_form", "12"))
        self.repeats_combo_box.setItemText(9, _translate("edit_form", "13"))
        self.repeats_combo_box.setItemText(10, _translate("edit_form", "14"))
        self.ok_button.setText(_translate("edit_form", "Ok"))
        self.cancel_button.setText(_translate("edit_form", "Cancel"))
        self.label_8.setText(_translate("edit_form", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Edit</span></p></body></html>"))
